site_name: Hello-IT Wiki
site_url: https://hello-it.zhicheng233.top
repo_url: https://github.com/ATCG-Studio/Hello-IT_Wik
repo_name: ATCG-Studio/Hello-IT_Wiki

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: ATCG-Studio/Hello-IT_Wik
      branch: main

theme:
  name: material
  language: zh
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
  palette: 
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

extra:
  consent:
    title: Cookie 许可
    description: >- 
      我们使用 Cookie 来识别您的重复访问和偏好，以及衡量我们的文档的有效性以及用户是否找到他们正在搜索的内容。
      同时我们使用Microsoft Clarity等第三方工具来收集用户行为数据，以便更好的优化我们的文档。
      在您的同意下，您正在帮助我们使我们的文档更好。
    actions:
      - accept
      - reject

copyright: >
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans" target="_blank">
    <img src="https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png" loading="lazy" alt="CC BY-NC-SA 4.0" />
  </a>
  © 2024-2025 ATCG Studio - 
  <a href="#__consent">更改 cookie 设置</a>
      
