#基本
site_name: Hello-IT Wiki
site_url: https://hello-it.zhicheng233.top/
repo_url: https://github.com/ATCG-Studio/Hello-IT_Wiki
repo_name: ATCG-Studio/Hello-IT_Wiki

#插件
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: ATCG-Studio/Hello-IT_Wik
      branch: main
      enabled: true
  - search

#主题
theme:
  #基础
  name: material
  language: zh
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs           # 导航标签
    - navigation.path           # 导航路径
    - content.action.edit       # 编辑操作
    - content.action.view       # 查看操作
    - content.code.annotate     # 代码注释
    - content.code.copy         # 复制代码
    - content.tabs.link         # 标签链接
    - content.tooltips          # 工具提示
    - navigation.indexes        # 导航索引
    - navigation.top            # 导航顶部
    - navigation.tracking       # 导航跟踪
    - search.highlight          # 搜索高亮
    - search.share              # 搜索分享
    - search.suggest            # 搜索建议
    - toc.follow                # 目录跟随

  #扩展主题
  custom_dir: overrides
  #多主题切换
  palette: 
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

#扩展
extra:
  # 评论系统
  disqus: 'open' 
  #Google分析
  analytics:
    provider: google
    property: G-F8VRX8RG09
    feedback:
      title: 此页面可读性如何？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 这个页面阅读很流畅，很明白~
          data: 1
          note: >-
            感谢您的反馈喵！
        - icon: material/emoticon-sad-outline
          name: 此页面可以改进!
          data: 0
          note: >- 
            感谢您的反馈喵！如果可以请通过邮件联系我们，帮助我们改进这个页面！ 
  #Cookie栏
  consent:
    title: Cookie 许可
    description: >- 
      我们使用 Cookie 来识别您的重复访问和偏好，以及衡量我们的文档的有效性以及用户是否找到他们正在搜索的内容。
      同时我们使用Google Clarity等第三方工具来收集用户行为数据，以便更好的优化我们的文档。
      在您的同意下，您正在帮助我们使我们的文档更好。
    actions:
      - accept
      - reject

#markdown扩展
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#版权声明
copyright: >
  <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans" target="_blank">
    <img src="https://licensebuttons.net/l/by-sa/4.0/88x31.png" loading="lazy" alt="CC BY-SA 4.0" />
  </a>
  © 2024-2025 ATCG Studio - 
  <a href="#__consent">更改 cookie 设置</a>
      
#导航
#导航排布| Hello-IT | 软件推荐表 | 贡献帮助文档 | 友情链接 | Blog
nav:
  #Hello-IT部分
  - Hello-IT: 
    - index.md
    - Windows:
      - Windows/index.md
    - Android:
      - Android/index.md
    - Linux:
      - Linux/index.md
    - MacOS:
      - MacOS/index.md
    - IOS:
      - IOS/index.md
    - 网上冲浪:
      - Web_surfing/index.md
    - GFW:
      - GFW/index.md
      - 什么是GFW?: GFW/what-is-gfw(block-cn).md
      - 如何翻墙?: GFW/How-to-bypass-gfw(block-cn).md
    - 软件:
      - Softwave/index.md
      - 安装Office: Softwave/Install_Office.md
    - 杂项:
      - Other/index.md
  #软件推荐表

  #贡献帮助文档
  - 贡献帮助文档:
    - Contribute-doc/index.md
    - 如何提交Pull Request?: Contribute-doc/How-to-PR.md
    - 规范约定: Contribute-doc/README.md